language: go

go:
  - "1.11.x"
  - "1.12.x"

branches:
  only:
  - master
  - develop

env:
  - GO111MODULE=on

services:
  - mysql

before_install:
  - echo "127.0.0.1 local" >> /etc/hosts

install:
  - cat /etc/hosts

script:
  - cd g
  - GOARCH=386 go test -v ./...
  - GOARCH=amd64 go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic


after_success:
  - bash <(curl -s https://codecov.io/bash)



