
# MySQL.
[database]
    [database.logger]
        Level   = "all"
        Stdout  = true
        CtxKeys = ["RequestId"]
    [database.default]
        link   = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
        debug  = true

# Redis.
[redis]
    default = "127.0.0.1:6379,0"
    cache   = "127.0.0.1:6379,1"

#[database]
#   [[database.default]]
#        type = "mysql"
#        link = "root:12345678@tcp(127.0.0.1:3306)/test?parseTime=true&loc=Local"
#





