version: '2'

services:
  apollo-quick-start:
    image: "loads/apollo-quick-start:latest"
    container_name: apollo-quick-start
    depends_on:
      - apollo-db
    ports:
      - "8080:8080"
      - "8070:8070"
      - "8060:8060"
    links:
      - apollo-db
    #environment:
      #JAVA_OPTS: '-Xms100m -Xmx1000m -Xmn100m -Xss256k -XX:MetaspaceSize=10m -XX:MaxMetaspaceSize=250m'
      #APOLLO_CONFIG_DB_USERNAME: 'root'
      #APOLLO_CONFIG_DB_PASSWORD: 'apollo'
      #APOLLO_PORTAL_DB_USERNAME: 'root'
      #APOLLO_PORTAL_DB_PASSWORD: 'apollo'

  apollo-db:
    image: "loads/mysql:5.7"
    container_name: apollo-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      #MYSQL_ROOT_PASSWORD: 'apollo'
    depends_on:
      - apollo-dbdata
    ports:
      - "13306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    volumes_from:
      - apollo-dbdata

  apollo-dbdata:
    image: "loads/alpine:3.8"
    container_name: apollo-dbdata
    volumes:
      - /var/lib/mysql
