

# redis配置
[[redis-cache]]
    db   = 0
    host = "192.168.0.100"
    port = 6379

[[redis-cache]]
    db   = 1
    host = "192.168.0.100"
    port = 6379

[[redis-disk]]
    db   = 0
    host = "192.168.0.100"
    port = 6380

[[redis-disk]]
    db   = 1
    host = "192.168.0.100"
    port = 6380

# memcache配置
[[memcache]]
    host   = "192.168.0.101"
    port   = 11211
    expire = 60

[[memcache]]
    host   = "192.168.0.102"
    port   = 11211
    expire = 60