# redis配置
[[redis-cache]]
    db   = 0
    host = "192.168.0.100"
    port = 6379

[[redis-cache]]
    db   = 1
    host = "192.168.0.100"
    port = 6379

[[redis-disk]]
    db   = 0
    host = "192.168.0.100"
    port = 6380

[[redis-disk]]
    db   = 1
    host = "192.168.0.100"
    port = 6380
