
[database]
	debug = true
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"

[redis]
    default  = "127.0.0.1:6379,0"
    cache = "127.0.0.1:6379,1"

# Logger.
[logger]
    Path        = "/tmp/log/gf-app"
    Level       = "all"
    Stdout      = true

[viewer]
    delimiters  =  ["${", "}"]
    autoencode  =  true


[server]
	Address     = ":8800"
	ServerRoot  = "/Users/john/Downloads"
	ServerAgent = "gf-app"
#	LogPath     = "./log/gf-app/server"