name: Deploy to GitHub Pages

on:
  push:
    branches:
      # - 'master'
      - 'doc-build'
    # 如果你想要进一步定义触发条件、路径等，可以查看文档
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  schedule:
    - cron: '0 15 * * *'
  # 非默认分支无法触发定时任务

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: doc-build
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Set Up Golang Environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
          cache: false
      - name: download goframe docs
        run: ./download.sh
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build

      # 部署到 GitHub Pages 的热门选择：
      # 文档：https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 要发布到 `gh-pages` 分支的构建输出：
          publish_dir: ./build
          # 下面两行会将此次部署 commit 的作者设置为官方的
          # GH-Actions 机器人：
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # 如果不设置这两个字段，GH actions 机器人会被默认使用。
          # 你可以用自己的用户信息替换它们。
          cname: pages.goframe.org
